options:
  do_ocr: false
  to_formats:
    - json

sources:
  - kind: snowflake
    account: "xy12345"
    user: "me"
    password: "changeme" # or use private_key / private_key_path instead
    warehouse: "MY_WH"
    database: "MY_DB"
    db_schema: "PUBLIC"
    stage: "MY_STAGE"
    # prefix: "incoming/"
    # pattern: ".*[.]pdf"
    max_num_elements: 10

target:
  kind: snowflake_doc
  account: "xy12345"
  user: "me"
  password: "changeme"
  warehouse: "MY_WH"
  database: "MY_DB"
  db_schema: "PUBLIC"
  table: "MY_TABLE"
  id_field: "doc_id"
  mappings:
    JSON: "CONTENT_JSON"
    TEXT: "CONTENT_TEXT"
    MARKDOWN: "CONTENT_MD"

  # kind: snowflake_chunk
