name: "Run CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-checks:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name != 'docling-project/docling-jobkit' && github.event.pull_request.head.repo.full_name != 'docling-project/docling-jobkit') }}
    uses: ./.github/workflows/job-checks.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
